export {
  addToast,
  calcTotal,
  cookieData,
  debounce,
  formHandler,
  formatDate,
  generateUserAvatar,
  getColorFromString,
  handleRequest,
  messages,
  randomKeyGenerator,
  submitForm,
  truncate,
  Authenticate,
} from "./general";
